"""
Semantic Analysis Module for TauTranslator Core Engine
======================================================

This module provides the core components for performing semantic analysis
on the Abstract Syntax Tree (AST) generated by the parser.

Exports:
    - SemanticAnalyzer: The main class for performing semantic analysis.
    - SemanticError: Exception class for semantic errors.
    - Symbol: Represents a symbol in the symbol table.
    - SymbolTable: Manages symbols and scopes.
    - TypeInfo: Represents type information for symbols and expressions.
    - ErrorCollector: Collects semantic errors during analysis.
"""

from .semantic_analyzer import SemanticAnalyzer
from .semantic_types import (
    SemanticError,
    Symbol,
    SymbolTable,
    TypeInfo,
    ErrorCollector
)

__all__ = [
    "SemanticAnalyzer",
    "SemanticError",
    "Symbol",
    "SymbolTable",
    "TypeInfo",
    "ErrorCollector",
]
